# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1184, 914)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(200, 50, 671, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 630, 961, 251))
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(290, 40, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(30, 100, 391, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(30, 150, 391, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(30, 200, 391, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(520, 150, 391, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(520, 200, 391, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(520, 100, 391, 31))
        self.label_17.setObjectName("label_17")

        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(490, 550, 221, 61))
        self.label_9.setAutoFillBackground(True)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("logo_lg.png"))
        self.label_9.setOpenExternalLinks(False)
        self.label_9.setObjectName("label_9")

        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(60, 140, 971, 371))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 270, 112, 34))
        self.pushButton_3.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(250, 180, 116, 22))
        self.checkBox.setObjectName("checkBox")
        self.loginBTN = QtWidgets.QPushButton(self.groupBox)
        self.loginBTN.setGeometry(QtCore.QRect(340, 270, 112, 34))
        self.loginBTN.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.loginBTN.setObjectName("loginBTN")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 110, 291, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(550, 50, 141, 101))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(250, 50, 291, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox.raise_()
        self.label_10.raise_()
        self.groupBox_2.raise_()
        self.label_9.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "TASKING MAP Parser 회원 가입"))
        self.groupBox_2.setTitle(_translate("Dialog", "GroupBox"))
        self.label_11.setText(_translate("Dialog", "TASKING News."))
        self.label_12.setText(_translate("Dialog", "[TASKING 컴파일러]  HEX 파일의 구조 Part 2"))
        self.label_13.setText(_translate("Dialog", "[TASKING 컴파일러]  HEX 파일의 구조 Part 2"))
        self.label_14.setText(_translate("Dialog", "[TASKING 컴파일러]  HEX 파일의 구조 Part 2"))
        self.label_15.setText(_translate("Dialog", "[TASKING 업데이트] 새로운 소식 확인해보세요"))
        self.label_16.setText(_translate("Dialog", "[TASKING 업데이트] 새로운 소식 확인해보세요"))
        self.label_17.setText(_translate("Dialog", "[TASKING 업데이트] 새로운 소식 확인해보세요"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.pushButton_3.setText(_translate("Dialog", "문의 하기"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
        self.loginBTN.setText(_translate("Dialog", "회원 가입"))
        self.pushButton.setText(_translate("Dialog", "로그인"))
# import gui_image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
